name: debug

on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - 'apks/**'
      - 'README.md'
      - 'CHANGELOG.md'
    branches:
      - 'master'

permissions:
  contents: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep -oP 'version=\K[^ ]+' module.prop)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Get Commit Hash
        id: get_commit_hash
        run: |
          COMMIT_HASH=$(git log --oneline -n 1 | awk '{print $1}' | cut -c1-7)  # Get first 7 characters of commit hash
          echo "commit_hash=$COMMIT_HASH" >> "$GITHUB_OUTPUT"

      - name: Update Module.prop
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          COMMIT_HASH=${{ steps.get_commit_hash.outputs.commit_hash }}
          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/$VERSION($COMMIT_HASH)/g" module.prop
          sed -i "s/versionCode=.*/versionCode=$(date +%Y%m%d)/g" module.prop

      - name: Generate Asset
        run: |
          sudo mkdir -p /box_for_root
          sudo cp -r --parents $(find ./ -type f ! -path './.git/*' ! -name 'CHANGELOG.md' ! -name 'update.json' ! -name 'build.sh' ! -path './.github/*' ! -path './apks/*')  /box_for_root/

      - name: Upload Debug Asset => (box_for_root-v${{ steps.get_version.outputs.version }}-${{ steps.get_commit_hash.outputs.commit_hash }}.zip)
        uses: actions/upload-artifact@v4
        with:
          name: box_for_root-v${{ steps.get_version.outputs.version }}-${{ steps.get_commit_hash.outputs.commit_hash }}
          path: /box_for_root/

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository (only if build is successful)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for [ci] in commit message
        id: check_ci
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"[ci]"* ]]; then
            echo "should_upload=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_upload=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run build
        if: steps.check_ci.outputs.should_upload == 'true'
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          COMMIT_HASH=${{ steps.get_commit_hash.outputs.commit_hash }}
          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/$VERSION($COMMIT_HASH)/g" module.prop
          zip -r -o -X -ll box_for_root-v${VERSION}-${COMMIT_HASH}.zip ./ \
            -x '.git/*' -x 'CHANGELOG.md' -x 'update.json' -x 'build.sh' -x '.github/*' -x 'apks/*'

      - name: Upload to GitHub Pre-release
        if: steps.check_ci.outputs.should_upload == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          COMMIT_HASH=${{ steps.get_commit_hash.outputs.commit_hash }}
          FILE=$(find . -name "*.zip")
          gh release create "pre-${VERSION}-${COMMIT_HASH}" "$FILE" \
            --prerelease \
            --title "Pre-release ${VERSION} (${COMMIT_HASH})" \
            --notes "pre-release build from commit ${COMMIT_HASH}"

      - name: Upload to Telegram
        if: steps.check_ci.outputs.should_upload == 'true'
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            export VERSION=${{ steps.get_version.outputs.version }}
            export COMMIT_HASH=${{ steps.get_commit_hash.outputs.commit_hash }}
            export COMMIT=$(git log --oneline -n 5 --no-decorate | sed 's/^[0-9a-f]* //' | sed 's/^/— /')
            FILE=$(find . -name "*.zip")
            pip3 install telethon==1.31.1
            python3 $GITHUB_WORKSPACE/.github/boxrootbot.py "$FILE"
          fi